annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - HomeAutomation
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'Shinobi Docker from official Dockerhub repo. Note to use GPU for hardware
  encoding or Object detection: 1. add `--runtime=nvidia` in Extra Parameters.  2.
  Add Nvidia GPU Devices variables ID & Driver capabilities in advanced'
home: https://github.com/truecharts/apps/tree/master/charts/stable/shinobi-pro-cctv
icon: https://truecharts.org/_static/img/appicons/shinobi-pro-cctv.png
keywords:
- shinobi-pro-cctv
- HomeAutomation
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: shinobi-pro-cctv
sources:
- https://gitlab.com/Shinobi-Systems/Shinobi
- https://hub.docker.com/r/shinobicctv/shinobi
type: application
version: 0.0.1
