annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Network-DNS
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: This Docker image will allow you to use the Hetzner DNS Service (https://www.hetzner.com/dns-console)
  as a Dynamic DNS (DDNS) Provider.
home: https://github.com/truecharts/apps/tree/master/charts/stable/hetzner-ddns
icon: https://truecharts.org/_static/img/appicons/hetzner-ddns.png
keywords:
- hetzner-ddns
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: hetzner-ddns
sources:
- https://github.com/kutzilla/docker-hetzner-ddns
- https://hub.docker.com/r/kutzilla/hetzner-ddns
type: application
version: 0.0.1
