annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - HomeAutomation
    - Productivity
    - Tools-Utilities
    - Network-Web
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "minimal ics / iCal / Calendar hoster, \r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/minimal-ics-hoster
icon: https://truecharts.org/_static/img/appicons/minimal-ics-hoster.png
keywords:
- minimal-ics-hoster
- HomeAutomation
- Productivity
- Tools-Utilities
- Network-Web
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: minimal-ics-hoster
sources:
- https://github.com/patrickstigler/minimal-ics-host/tree/master
- https://hub.docker.com/r/patrickstigler/minimal-ics-hoster
type: application
version: 0.0.1
