annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Network-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'Run a Pritunl VPN Server [br][br]

  '
home: https://github.com/truecharts/apps/tree/master/charts/stable/pritunl
icon: https://truecharts.org/_static/img/appicons/pritunl.png
keywords:
- pritunl
- Network-Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: pritunl
sources:
- https://pritunl.com/
- https://hub.docker.com/r/bashninja/docker-pritunl/
type: application
version: 0.0.1
