annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - MediaApp
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A super-sexy voice interface for the Plex HTPC.
home: https://github.com/truecharts/apps/tree/master/charts/stable/flextv
icon: https://truecharts.org/_static/img/appicons/flextv.png
keywords:
- flextv
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: flextv
sources:
- https://github.com/d8ahazard/FlexTV
- https://registry.hub.docker.com/r/jcreynolds/flextv/
type: application
version: 0.0.1
