annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This container will download and install a StarMade Dedicated Server.\
  \ It will also install a basic server.cfg at the first startup.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/StarMade
icon: https://truecharts.org/_static/img/appicons/StarMade.png
keywords:
- starmade
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: StarMade
sources:
- https://www.star-made.org/
- https://hub.docker.com/r/ich777/starmade-server/
type: application
version: 0.0.1
