annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Downloaders
    - MediaApp-Books
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "**FMD2:** This is an active fork of the Free Manga Downloader which\
  \ is a free open source application written in Object Pascal for managing and downloading\
  \ manga from various websites.  \r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/fmd2-wine
icon: https://truecharts.org/_static/img/appicons/fmd2-wine.png
keywords:
- fmd2-wine
- Downloaders
- MediaApp-Books
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: fmd2-wine
sources:
- https://github.com/Banh-Canh/docker-FMD2
- https://hub.docker.com/r/banhcanh/docker-fmd2/
type: application
version: 0.0.1
