annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Network
    - Network-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'Tixati is a New and Powerful P2P System

  '
home: https://github.com/truecharts/apps/tree/master/charts/stable/Tixati
icon: https://truecharts.org/_static/img/appicons/Tixati.png
keywords:
- tixati
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: Tixati
sources:
- https://www.tixati.com/
- https://hub.docker.com/r/angelics/unraid-docker-tixati
type: application
version: 0.0.1
