annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A self-hosted blogging platform in which posts are written in markdown
home: https://github.com/truecharts/apps/tree/master/charts/stable/hexo-blog
icon: https://truecharts.org/_static/img/appicons/hexo-blog.png
keywords:
- hexo-blog
- Productivity
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: hexo-blog
sources:
- https://github.com/fletchto99/hexo-dev-docker
- https://hub.docker.com/r/fletchto99/hexo-dev-blog/
type: application
version: 0.0.1
