annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Livebook is a web application for writing interactive and collaborative
  code notebooks for Elixir
home: https://github.com/truecharts/apps/tree/master/charts/stable/livebook
icon: https://truecharts.org/_static/img/appicons/livebook.png
keywords:
- livebook
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: livebook
sources:
- https://livebook.dev/
- https://hub.docker.com/r/livebook/livebook
type: application
version: 0.0.1
