annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Downloaders
    - MediaApp-Video
    - MediaServer-Video
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "TubeSync is a PVR (personal video recorder) for YouTube. Or, like Sonarr\
  \ but for YouTube (with a built-in download client). It is designed to synchronize\
  \ channels and playlists from YouTube to local directories and update your media\
  \ server once media is downloaded.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/tubesync
icon: https://truecharts.org/_static/img/appicons/tubesync.png
keywords:
- tubesync
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: tubesync
sources:
- https://github.com/meeb/tubesync
- https://registry.hub.docker.com/r/ghcr.io/meeb/tubesync
type: application
version: 0.0.1
