annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools-Utilities
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: DIY tool to create and print labels for Dell Poweredge and HP Proliant
  drive caddies.
home: https://github.com/truecharts/apps/tree/master/charts/stable/homelablabelmaker
icon: https://truecharts.org/_static/img/appicons/homelablabelmaker.png
keywords:
- homelablabelmaker
- Tools-Utilities
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: homelablabelmaker
sources:
- https://github.com/DavidSpek/homelablabelmaker
- https://hub.docker.com/r/davidspek/homelablabelmaker/
type: application
version: 0.0.1
