annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Cloud
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "ecoDMS 18.09 (apu) Full Installation - Document Management System (DMS)\
  \ - Audit-compliant archive for scanning, archiving, managing and retrieving all\
  \ data and documents.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/ecodms
icon: https://truecharts.org/_static/img/appicons/ecodms.png
keywords:
- ecodms
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: ecodms
sources:
- https://www.ecodms.de/index.php/en/
- https://hub.docker.com/r/ecodms/allinone-18.09/
type: application
version: 0.0.1
