annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Backup
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Like to maintain your own data? Automatically backup your github account
  to your Unraid server on a schedule.
home: https://github.com/truecharts/apps/tree/master/charts/stable/github-backup
icon: https://truecharts.org/_static/img/appicons/github-backup.png
keywords:
- github-backup
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: github-backup
sources:
- https://hub.docker.com/r/lnxd/github-backup
type: application
version: 0.0.1
