annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - MediaServer-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Media display for Plex, sonarr and radarr
home: https://github.com/truecharts/apps/tree/master/charts/stable/posterr
icon: https://truecharts.org/_static/img/appicons/posterr.png
keywords:
- posterr
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: posterr
sources:
- https://github.com/petersem/posterr
- https://hub.docker.com/r/petersem/posterr/
type: application
version: 0.0.1
