annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This Docker will download and install SteamCMD. It will also install\
  \ Starbound (Valid Steam useraccount with the game purchased and Steam Guard disabled\
  \ required) and run it.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/starbound
icon: https://truecharts.org/_static/img/appicons/starbound.png
keywords:
- starbound
- GameServers
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: starbound
sources:
- https://www.steampowered.com/
- https://hub.docker.com/r/ich777/steamcmd/
type: application
version: 0.0.1
