annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Backup
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A new generation cross-platform cloud backup tool.
home: https://github.com/truecharts/apps/tree/master/charts/stable/duplicacy
icon: https://truecharts.org/_static/img/appicons/duplicacy.png
keywords:
- duplicacy
- Backup
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: duplicacy
sources:
- https://hotio.dev/containers/duplicacy
- https://hub.docker.com/r/hotio/duplicacy
type: application
version: 0.0.1
