annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
    - MediaApp-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A utility to help manage your library. Options include adding 4k banners
  and HDR banners to your poster art automactically, auto collections for Disney and
  Pixar Studios and hiding/auto optimising media files where there is only a 4k version
  available.
home: https://github.com/truecharts/apps/tree/master/charts/stable/plex-utills
icon: https://truecharts.org/_static/img/appicons/plex-utills.png
keywords:
- plex-utills
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: plex-utills
sources:
- https://github.com/jkirkcaldy/plex-utills
- https://hub.docker.com/r/jkirkcaldy/plex-utills/
type: application
version: 0.0.1
