annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Productivity
    - Tools-Utilities
    - MediaApp-Photos
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "DESCRIPTION\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/freecad-desktop-g3
icon: https://truecharts.org/_static/img/appicons/freecad-desktop-g3.png
keywords:
- freecad-desktop-g3
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: freecad-desktop-g3
sources:
- https://github.com/accetto/headless-drawing-g3/
- https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-freecad-g3
type: application
version: 0.0.1
