annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Backup
    - Cloud
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'A simple way to backup important files to Google Cloud Storage.

  '
home: https://github.com/truecharts/apps/tree/master/charts/stable/google-cloud-storage-backup
icon: https://truecharts.org/_static/img/appicons/google-cloud-storage-backup.png
keywords:
- google-cloud-storage-backup
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: google-cloud-storage-backup
sources:
- https://hub.docker.com/r/vinid223/gcloud-storage-backup
type: application
version: 0.0.1
