annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Downloaders
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Trackarr monitors tracker announce IRC channel, parses the announcements,
  and forwards those announcements to ARR PVRs (eg Sonarr).
home: https://github.com/truecharts/apps/tree/master/charts/stable/trackarr
icon: https://truecharts.org/_static/img/appicons/trackarr.png
keywords:
- trackarr
- Downloaders
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: trackarr
sources:
- https://hotio.dev/containers/trackarr
- https://hub.docker.com/r/hotio/trackarr
type: application
version: 0.0.1
