annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Snippet Box is a simple self-hosted app for organizing your code snippets.
  It allows you to easily create, edit, browse and manage your snippets in various
  languages.
home: https://github.com/truecharts/apps/tree/master/charts/stable/snippet-box
icon: https://truecharts.org/_static/img/appicons/snippet-box.png
keywords:
- snippet-box
- Productivity
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: snippet-box
sources:
- https://github.com/pawelmalak/snippet-box
- https://hub.docker.com/r/pawelmalak/snippet-box
type: application
version: 0.0.1
