annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Downloaders
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Transmission is designed for easy, powerful use. Transmission has the\
  \ features you want from a BitTorrent client: encryption, a web interface, peer\
  \ exchange, magnet links, DHT, \xB5TP, UPnP and NAT-PMP port forwarding, webseed\
  \ support, watch directories, tracker editing, global and per-torrent speed limits,\
  \ and more.[br]\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/transmission-nzbtomedia
icon: https://truecharts.org/_static/img/appicons/transmission-nzbtomedia.png
keywords:
- transmission-nzbtomedia
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: transmission-nzbtomedia
sources:
- http://www.transmissionbt.com/
- https://hub.docker.com/r/thraxis/transmission-nzbtomedia/
type: application
version: 0.0.1
