annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "A simple container that opens OpenRGB in a browser so that you can control\
  \ all of your System lighting while still running UnraidOS.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/p3r-openrgb
icon: https://truecharts.org/_static/img/appicons/p3r-openrgb.png
keywords:
- p3r-openrgb
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: p3r-openrgb
sources:
- https://github.com/P3R-CO/openrgb-container
- https://hub.docker.com/repository/docker/p3rco/openrgb
type: application
version: 0.0.1
