annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'QuakeJS is a port of ioquake3 to JavaScript with the help of Emscripten.[br]IMPORTANT
  Use Custom:br0 https://youtu.be/2VnQxxn00jU?t=121 put Fixed IP address, then copy
  the ip and access it using you broswer [BR][span style=''color: #ff9900;''][B]DON''T
  USE BRIDGE I''M NOT RESPONSABLE FOR UNRAID CONFLICTING WITH PORT 80 FOR THIS DOCKER[/B]'
home: https://github.com/truecharts/apps/tree/master/charts/stable/quakejs
icon: https://truecharts.org/_static/img/appicons/quakejs.png
keywords:
- quakejs
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: quakejs
sources:
- https://github.com/treyyoder/quakejs-docker
- https://hub.docker.com/r/treyyoder/quakejs/
type: application
version: 0.0.1
