annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Network-Voip
    - Network-Messenger
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Jicofo image for Jitsi Meet
home: https://github.com/truecharts/apps/tree/master/charts/stable/jitsi-jicofo
icon: https://truecharts.org/_static/img/appicons/jitsi-jicofo.png
keywords:
- jitsi-jicofo
- Productivity
- Network-Voip
- Network-Messenger
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: jitsi-jicofo
sources:
- https://jitsi.org/
- https://hub.docker.com/r/jitsi/jicofo/
type: application
version: 0.0.1
