annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Backup
    - Cloud
    - Downloaders
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'iCloudPD, Alpine Linux Docker container wrriten by [a href="https://github.com/boredazfcuk"]boredazfcuk[/a],
  syncs photos from iDevices to a single directory on Unraid. It uses the system keyring
  to securely store credentials, has HEIC to JPG conversion capability, and supports
  Telegram, Prowl, PushBullet and WebHook notifications.

  '
home: https://github.com/truecharts/apps/tree/master/charts/stable/icloudpd
icon: https://truecharts.org/_static/img/appicons/icloudpd.png
keywords:
- icloudpd
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: icloudpd
sources:
- https://github.com/Womabre/-unraid-docker-templates
- https://hub.docker.com/r/boredazfcuk/icloudpd/
type: application
version: 0.0.1
