annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: This program runs a speedtest check every hour and graphs the results.
  The back-end is written in Laravel and the front-end uses React. It uses the speedtest-cli
  package to get the data and uses Chart.js to plot the results.
home: https://github.com/truecharts/apps/tree/master/charts/stable/speedtest-tracker
icon: https://truecharts.org/_static/img/appicons/speedtest-tracker.png
keywords:
- speedtest-tracker
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: speedtest-tracker
sources:
- https://hub.docker.com/r/henrywhitaker3/speedtest-tracker
- https://hub.docker.com/r/henrywhitaker3/speedtest-tracker/
type: application
version: 0.0.1
