annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Network-DNS
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Technitium DNS Server is an open source tool that can be used for self
  hosting a local DNS server for privacy and security or, used for experimentation/testing
  by software developers on their computer. It works out-of-the-box with no or minimal
  configuration and provides a user friendly web console accessible using any web
  browser.
home: https://github.com/truecharts/apps/tree/master/charts/stable/ts-dnsserver
icon: https://truecharts.org/_static/img/appicons/ts-dnsserver.png
keywords:
- ts-dnsserver
- Network-DNS
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: ts-dnsserver
sources:
- https://github.com/TechnitiumSoftware/DnsServer
- https://hub.docker.com/r/roxedus/ts-dnsserver/
type: application
version: 0.0.1
