annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "A automated pre-roll program for your plex pre-roll needs.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/rollarr
icon: https://truecharts.org/_static/img/appicons/rollarr.png
keywords:
- rollarr
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: rollarr
sources:
- https://github.com/TheHumanRobot/Rollarr
- https://hub.docker.com/r/thehumanrobot/rollarr/
type: application
version: 0.0.1
