annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - HomeAutomation
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Enjoy Prusaslicer directly in your browser with this easy to use Docker\
  \ container.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/prusaslicer-novnc
icon: https://truecharts.org/_static/img/appicons/prusaslicer-novnc.png
keywords:
- prusaslicer-novnc
- HomeAutomation
- Productivity
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: prusaslicer-novnc
sources:
- https://www.prusa3d.com/prusaslicer/
- https://hub.docker.com/r/mikeah/prusaslicer-novnc
type: application
version: 0.0.1
