annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Downloaders
    - MediaApp-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "gPodder is a simple, open source podcast client written in Python using\
  \ GTK+. In development since 2005 with a proven, mature codebase.&amp;#xD;\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/gpodder
icon: https://truecharts.org/_static/img/appicons/gpodder.png
keywords:
- gpodder
- Downloaders
- MediaApp-Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: gpodder
sources:
- https://gpodder.github.io/
- https://hub.docker.com/r/xthursdayx/gpodder-docker/
type: application
version: 0.0.1
