annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
    - Network-Web
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Flame is self-hosted startpage for your server. Easily manage your apps
  and bookmarks with built-in editors.
home: https://github.com/truecharts/apps/tree/master/charts/stable/flame
icon: https://truecharts.org/_static/img/appicons/flame.png
keywords:
- flame
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: flame
sources:
- https://github.com/pawelmalak/flame
- https://hub.docker.com/r/pawelmalak/flame
type: application
version: 0.0.1
