annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Security
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: PWM is a free and opensource password self-service application enabling
  end-users to reset their enterprise password themselves.
home: https://github.com/truecharts/apps/tree/master/charts/stable/pwm
icon: https://truecharts.org/_static/img/appicons/pwm.png
keywords:
- pwm
- Security
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: pwm
sources:
- https://github.com/pwm-project/pwm
- https://hub.docker.com/r/fjudith/pwm
type: application
version: 0.0.1
