annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - HomeAutomation
    - Tools-Utilities
    - Other
    - MediaApp-Other
    - MediaServer-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Invitarr is a chatbot that invites discord users to plex. You can also
  automate this bot to invite discord users to plex once a certain role is given to
  a user or the user can also be added manually.
home: https://github.com/truecharts/apps/tree/master/charts/stable/Invitarr
icon: https://truecharts.org/_static/img/appicons/Invitarr.png
keywords:
- invitarr
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: Invitarr
sources:
- https://github.com/Sleepingpirates/Invitarr
- https://hub.docker.com/r/piratify/invitarr
type: application
version: 0.0.1
