annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: RedisInsight - The GUI for Redis.
home: https://github.com/truecharts/apps/tree/master/charts/stable/redisinsight
icon: https://truecharts.org/_static/img/appicons/redisinsight.png
keywords:
- redisinsight
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: redisinsight
sources:
- https://redis.com/redis-enterprise/redis-insight/
- https://hub.docker.com/r/redislabs/redisinsight
type: application
version: 0.0.1
