annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - HomeAutomation
    - Network-Management
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Tasmota backup - TasmoBackup - Backup all your tasmota devices in one
  place.  Add/scan for your Tasmota devices.  Use the backupall.php page to schedule
  automated backups of all devices!
home: https://github.com/truecharts/apps/tree/master/charts/stable/tasmobackup
icon: https://truecharts.org/_static/img/appicons/tasmobackup.png
keywords:
- tasmobackup
- HomeAutomation
- Network-Management
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: tasmobackup
sources:
- https://hub.docker.com/r/danmed/tasmobackupv1/
type: application
version: 0.0.1
