annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - GameServers
    - Network-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This Docker image can be used to create a video streaming server that\
  \ supports RTMP, HLS, DASH out of the box. It also allows adaptive streaming and\
  \ custom transcoding of video streams. All modules are built from source on Debian\
  \ and Alpine Linux base images.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/RTMPServer
icon: https://truecharts.org/_static/img/appicons/RTMPServer.png
keywords:
- rtmpserver
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: RTMPServer
sources:
- https://github.com/TareqAlqutami/rtmp-hls-server
- https://hub.docker.com/r/alqutami/rtmp-hls
type: application
version: 0.0.1
