annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: '- media

    - test

    '
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: API Support for your favorite torrent trackers.
home: https://github.com/truecharts/apps/tree/master/charts/stable/jackett
icon: https://truecharts.org/_static/img/appicons/jackett.png
keywords: []
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: lancache-bundle
sources: []
type: application
version: 0.0.1
