annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Cloud
    - Network-Web
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Get Google search results, but without any ads, javascript, AMP links,\
  \ cookies, or IP address tracking. Also includes a dark mode.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/whoogle-search
icon: https://truecharts.org/_static/img/appicons/whoogle-search.png
keywords:
- whoogle-search
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: whoogle-search
sources:
- https://github.com/benbusby/whoogle-search
- https://hub.docker.com/r/benbusby/whoogle-search/
type: application
version: 0.0.1
