annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This is a Basic Vintage Story Server it will download and install Vintage\
  \ Story Server and run it.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/Vintage-Story
icon: https://truecharts.org/_static/img/appicons/Vintage-Story.png
keywords:
- vintage-story
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: Vintage-Story
sources:
- https://www.vintagestory.at/
- https://hub.docker.com/r/ich777/vintagestory/
type: application
version: 0.0.1
