annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Alternative front-end for Google Translate, serving as a Free and Open
  Source translator with over a hundred languages available
home: https://github.com/truecharts/apps/tree/master/charts/stable/lingva
icon: https://truecharts.org/_static/img/appicons/lingva.png
keywords:
- lingva
- Productivity
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: lingva
sources:
- https://github.com/TheDavidDelta/lingva-translate
- https://hub.docker.com/r/thedaviddelta/lingva-translate
type: application
version: 0.0.1
