annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Docker container to run a GOG Starbound Server.
home: https://github.com/truecharts/apps/tree/master/charts/stable/starbound-gog-server
icon: https://truecharts.org/_static/img/appicons/starbound-gog-server.png
keywords:
- starbound-gog-server
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: starbound-gog-server
sources:
- https://hub.docker.com/r/bashninja/docker-gog-starbound-server/
type: application
version: 0.0.1
