annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - MediaApp-Video
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "TvhProxy is a small flask app to proxy requests between Plex Media Server\
  \ and Tvheadend.You have to run this Docker Container as a seperate IP Address.\
  \ This Function is supportet with UNRAID 6.4[br]\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/tvhproxy
icon: https://truecharts.org/_static/img/appicons/tvhproxy.png
keywords:
- tvhproxy
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: tvhproxy
sources:
- https://hub.docker.com/r/chvb/docker-tvhproxy
type: application
version: 0.0.1
