annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This Docker will download and install ioquake3 Server (You have to copy\
  \ your pak0.pk3 file from your game directory to your server).\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/ioquake3
icon: https://truecharts.org/_static/img/appicons/ioquake3.png
keywords:
- ioquake3
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: ioquake3
sources:
- https://ioquake3.org/
- https://hub.docker.com/r/ich777/ioquake3
type: application
version: 0.0.1
