annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - MediaApp-Other
    - Tools-Utilities
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'PASTA - Audio and Subtitle Track Changer for Plex [br]

  '
home: https://github.com/truecharts/apps/tree/master/charts/stable/PASTA
icon: https://truecharts.org/_static/img/appicons/PASTA.png
keywords:
- pasta
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: PASTA
sources:
- https://github.com/cglatot/pasta
- https://hub.docker.com/r/cglatot/pasta
type: application
version: 0.0.1
