annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Cloud
    - Network
    - Crypto
    - Downloaders
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Urbit is a clean-slate OS and network for the 21st century. Self-host
  your computer, identity and access to the urbit world.
home: https://github.com/truecharts/apps/tree/master/charts/stable/urbit
icon: https://truecharts.org/_static/img/appicons/urbit.png
keywords:
- urbit
- Cloud
- Network
- Crypto
- Downloaders
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: urbit
sources:
- https://urbit.org/
- https://hub.docker.com/r/tloncorp/urbit
type: application
version: 0.0.1
