annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This will run a TrackMania 2020 server. You can also install the EvoSC\
  \ to get an admin interface in the game.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/trackmania2020-server
icon: https://truecharts.org/_static/img/appicons/trackmania2020-server.png
keywords:
- trackmania2020-server
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: trackmania2020-server
sources:
- https://github.com/EvoTM/docker-trackmania
- https://hub.docker.com/r/evotm/trackmania
type: application
version: 0.0.1
