annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This Docker will download and install SteamCMD. It will also install\
  \ Unturned and run it (if you want to install Rocket Mod set the Variable 'Install\
  \ Rocket Mod' to 'true' without quotes).\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/unturned
icon: https://truecharts.org/_static/img/appicons/unturned.png
keywords:
- unturned
- GameServers
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: unturned
sources:
- https://www.steampowered.com/
- https://hub.docker.com/r/ich777/steamcmd/
type: application
version: 0.0.1
