annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools-Utilities
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "pixelserv-tls is a tiny bespoke HTTP/1.1 webserver with HTTPS and SNI\
  \ support. It acts on behalf of hundreds of thousands of advert/tracker servers\
  \ and responds to all requests with nothing to speed up web browsing.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/pixelserv-tls
icon: https://truecharts.org/_static/img/appicons/pixelserv-tls.png
keywords:
- pixelserv-tls
- Tools-Utilities
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: pixelserv-tls
sources:
- https://github.com/imTHAI/docker-pixelserv-tls
- https://hub.docker.com/r/imthai/pixelserv-tls/
type: application
version: 0.0.1
