annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Network-Other
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Electrum is a Bitcoin wallet focused on speed and simplicity, with low\
  \ resource usage. It uses remote servers that handle the most complicated parts\
  \ of the Bitcoin system, and it allows you to recover your wallet from a secret\
  \ phrase.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/electrum
icon: https://truecharts.org/_static/img/appicons/electrum.png
keywords:
- electrum
- Network-Other
- Productivity
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: electrum
sources:
- https://electrum.org/
- https://hub.docker.com/r/ich777/electrum
type: application
version: 0.0.1
