annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - HomeAutomation
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Build agents that monitor and act on your behalf. Your agents are standing\
  \ by! \r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/huginn
icon: https://truecharts.org/_static/img/appicons/huginn.png
keywords:
- huginn
- HomeAutomation
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: huginn
sources:
- https://github.com/huginn/huginn/
- https://hub.docker.com/r/huginn/huginn/
type: application
version: 0.0.1
