annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Backup
    - Cloud
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A simple way to backup important files to Amazon S3 and Glacier.
home: https://github.com/truecharts/apps/tree/master/charts/stable/s3backup
icon: https://truecharts.org/_static/img/appicons/s3backup.png
keywords:
- s3backup
- Backup
- Cloud
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: s3backup
sources:
- https://registry.hub.docker.com/r/joch/s3backup/
type: application
version: 0.0.1
