annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - MediaApp-Video
    - MediaApp-Music
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: An instance of kdenlive accessible through vnc and noVnc (=Web Interface)
home: https://github.com/truecharts/apps/tree/master/charts/stable/kdenlive-vnc
icon: https://truecharts.org/_static/img/appicons/kdenlive-vnc.png
keywords:
- kdenlive-vnc
- MediaApp-Video
- MediaApp-Music
- Productivity
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: kdenlive-vnc
sources:
- https://github.com/JonathanTreffler/kdenlive-vnc-docker
- https://hub.docker.com/r/tessypowder/docker-kdenlive/
type: application
version: 0.0.1
