annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Productivity
    - Tools-Utilities
    - Network-Management
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: This is a container with a webGUI to manage a Dell servers fan speeds
  using IPMI. You must enable IPMI from iDRAC. You can pass credentials through environment
  variables or enter them in the webGUI at runtime.
home: https://github.com/truecharts/apps/tree/master/charts/stable/ipmi-tools
icon: https://truecharts.org/_static/img/appicons/ipmi-tools.png
keywords:
- ipmi-tools
- Productivity
- Tools-Utilities
- Network-Management
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: ipmi-tools
sources:
- https://github.com/EdwardChamberlain/IPMI-Fan-Controller
- https://hub.docker.com/r/edchamberlain/ipmi-tools
type: application
version: 0.0.1
