annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: mproved Go Playground powered by Monaco Editor and React
home: https://github.com/truecharts/apps/tree/master/charts/stable/go-playground
icon: https://truecharts.org/_static/img/appicons/go-playground.png
keywords:
- go-playground
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: go-playground
sources:
- https://hub.docker.com/r/x1unix/go-playground
- https://hub.docker.com/r/x1unix/go-playground
type: application
version: 0.0.1
