annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'Tool to add new movies to Radarr based on RSS, IMDB and Trakt lists.
  You need to create your config file before running the image. For more info on setup
  of your config file, check out: https://hub.docker.com/r/lightglitch/seekerr/'
home: https://github.com/truecharts/apps/tree/master/charts/stable/seekerr
icon: https://truecharts.org/_static/img/appicons/seekerr.png
keywords:
- seekerr
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: seekerr
sources:
- https://github.com/lightglitch/seekerr
- https://hub.docker.com/r/lightglitch/seekerr/
type: application
version: 0.0.1
