annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Cloud
    - Network-Management
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'Docker Registry is used to store and distribute Docker images using
  HTTP API. This allows you host your own private Registry and store your images.
  Uses official Docker Registry image @ https://hub.docker.com/_/registry/

  '
home: https://github.com/truecharts/apps/tree/master/charts/stable/dockerregistry
icon: https://truecharts.org/_static/img/appicons/dockerregistry.png
keywords:
- dockerregistry
- Cloud
- Network-Management
- Productivity
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: dockerregistry
sources:
- https://github.com/distribution/distribution
- https://registry.hub.docker.com/_/registry/
type: application
version: 0.0.1
