annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Downloaders
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This python-based script automates downloads for JDownloader crawling\
  \ web feeds.[br]\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/feedcrawler
icon: https://truecharts.org/_static/img/appicons/feedcrawler.png
keywords:
- feedcrawler
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: feedcrawler
sources:
- https://github.com/rix1337/FeedCrawler
- https://registry.hub.docker.com/r/rix1337/docker-feedcrawler
type: application
version: 0.0.1
