annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: The to-do app to organize your life.
home: https://github.com/truecharts/apps/tree/master/charts/stable/vikunja-api
icon: https://truecharts.org/_static/img/appicons/vikunja-api.png
keywords:
- vikunja-api
- Productivity
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: vikunja-api
sources:
- https://vikunja.io/
- https://hub.docker.com/r/vikunja/api/
type: application
version: 0.0.1
