annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This Docker Container will download the latest stable release of the\
  \ game, generate the map and you're ready to play.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/factorio
icon: https://truecharts.org/_static/img/appicons/factorio.png
keywords:
- factorio
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: factorio
sources:
- https://www.factorio.com/
- https://hub.docker.com/r/factoriotools/factorio/
type: application
version: 0.0.1
