annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Network-Voip
    - Network-Messenger
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: FreePBX is a web-based open-source graphical user interface that manages
  Asterisk, a voice over IP and telephony server.
home: https://github.com/truecharts/apps/tree/master/charts/stable/freepbx
icon: https://truecharts.org/_static/img/appicons/freepbx.png
keywords:
- freepbx
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: freepbx
sources:
- https://github.com/tiredofit/docker-freepbx/
- https://hub.docker.com/r/tiredofit/freepbx/
type: application
version: 0.0.1
