annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Security
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "KeePassXC in a container.  Keep your passwords safe!\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/p3r-keepassxc
icon: https://truecharts.org/_static/img/appicons/p3r-keepassxc.png
keywords:
- p3r-keepassxc
- Security
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: p3r-keepassxc
sources:
- https://github.com/P3R-CO/keepassxc-container
- https://hub.docker.com/repository/docker/p3rco/keepassxc
type: application
version: 0.0.1
