annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Productivity
    - Security
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'Pomerium is an identity-aware proxy that enables secure access to internal
  applications. Pomerium provides a standardized interface to add access control to
  applications regardless of whether the application itself has authorization or authentication
  baked-in. Pomerium gateways both internal and external requests, and can be used
  in situations where you''d typically reach for a VPN. Check ports to ensure you
  do not have conflicts. **NOTE** You MUST: 1.Create a config.yaml file in appdata/pomerium/pomerium.
  The parameters for the file can be found here: https://www.pomerium.io/reference/
  2. Match your cookie secret in both the file and the variable below.'
home: https://github.com/truecharts/apps/tree/master/charts/stable/pomerium
icon: https://truecharts.org/_static/img/appicons/pomerium.png
keywords:
- pomerium
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: pomerium
sources:
- https://github.com/pomerium/pomerium
- https://hub.docker.com/r/pomerium/pomerium
type: application
version: 0.0.1
