annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Drone is a Continuous Integration platform built on Docker
home: https://github.com/truecharts/apps/tree/master/charts/stable/drone
icon: https://truecharts.org/_static/img/appicons/drone.png
keywords:
- drone
- Productivity
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: drone
sources:
- https://github.com/harness/drone
- https://hub.docker.com/r/drone/drone/
type: application
version: 0.0.1
