annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Valetudo-RE companion service for generating PNG maps.\r"
home: https://github.com/truecharts/apps/tree/master/charts/stable/valetudo-mapper
icon: https://truecharts.org/_static/img/appicons/valetudo-mapper.png
keywords:
- valetudo-mapper
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: valetudo-mapper
sources:
- https://github.com/rand256/valetudo-mapper
- https://hub.docker.com/r/rand256/valetudo-mapper/
type: application
version: 0.0.1
