annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Genea allows visually building and editing a family tree online. It consumes
  and saves genealogy data in the GEDCOM format without any server side components.
home: https://github.com/truecharts/apps/tree/master/charts/stable/genea
icon: https://truecharts.org/_static/img/appicons/genea.png
keywords:
- genea
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: genea
sources:
- https://github.com/genea-app/genea-app
- https://hub.docker.com/r/biggiesize/genea-app
type: application
version: 0.0.1
