annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: ROOT is a framework for data processing, born at CERN, at the heart of
  the research on high-energy physics. Every day, thousands of physicists use ROOT
  applications to analyze their data or to perform simulations.
home: https://github.com/truecharts/apps/tree/master/charts/stable/root
icon: https://truecharts.org/_static/img/appicons/root.png
keywords:
- root
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: root
sources:
- https://root.cern/
- https://hub.docker.com/repository/docker/bgameiro/arch-cern-root
type: application
version: 0.0.1
