annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Shoko server is the core component of the Shoko suite and with it's client-server
  architecture which allows any program or plugin to access Shoko. You'll have access
  to your entire collection locally and over the internet with no additional work
  outside the initial configuration required.
home: https://github.com/truecharts/apps/tree/master/charts/stable/shoko-server
icon: https://truecharts.org/_static/img/appicons/shoko-server.png
keywords:
- shoko-server
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: shoko-server
sources:
- https://github.com/ShokoAnime/ShokoServer
- https://hub.docker.com/r/shokoanime/server/
type: application
version: 0.0.1
