annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Web-based MongoDB admin interface, written with Node.js and express.
home: https://github.com/truecharts/apps/tree/master/charts/stable/mongo-express
icon: https://truecharts.org/_static/img/appicons/mongo-express.png
keywords:
- mongo-express
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: mongo-express
sources:
- https://registry.hub.docker.com/r/ulisses1478/mongo-express
type: application
version: 0.0.1
