annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Additinal processing node for FileFlows.  See http://fileflows.com for
  more information
home: https://github.com/truecharts/apps/tree/master/charts/stable/fileflows-node
icon: https://truecharts.org/_static/img/appicons/fileflows-node.png
keywords:
- fileflows-node
- Productivity
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: fileflows-node
sources:
- https://fileflows.com/
- https://hub.docker.com/r/revenz/fileflows-node/
type: application
version: 0.0.1
