annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Network-Other
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Trango self-hosted is a calling and file sharing solution that works\
  \ over LAN (local area networks). It does not need to involve the internet for calling\
  \ or file sharing. Ideal for offices, hotels, houses, restaurants, and any space\
  \ where people use the same Public IP address or the same Wi-Fi network. The package\
  \ comes with a discovery server and a web app that can be deployed on the local\
  \ machine and can be accessed from anywhere in the network.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/trango
icon: https://truecharts.org/_static/img/appicons/trango.png
keywords:
- trango
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: trango
sources:
- https://trango.io/
- https://hub.docker.com/r/tak786/trango-self-hosted
type: application
version: 0.0.1
