annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Rdesktop(http://xrdp.org/) - Containers containing full desktop environments
  in many popular flavors for Alpine, Ubuntu, Arch, and Fedora accessible via RDP.
home: https://github.com/truecharts/apps/tree/master/charts/stable/rdesktop
icon: https://truecharts.org/_static/img/appicons/rdesktop.png
keywords:
- rdesktop
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: rdesktop
sources:
- http://xrdp.org/
- https://github.com/orgs/linuxserver/packages/container/package/rdesktop
- https://github.com/linuxserver/docker-rdesktop#readme
type: application
version: 0.0.1
