annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Backup
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'Rest Server is a high performance HTTP server that implements restic''s
  REST backend API. It provides secure and efficient way to backup data remotely,
  using restic backup client via the rest: URL.'
home: https://github.com/truecharts/apps/tree/master/charts/stable/restic-rest-server
icon: https://truecharts.org/_static/img/appicons/restic-rest-server.png
keywords:
- restic-rest-server
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: restic-rest-server
sources:
- https://github.com/restic/rest-server
- https://hub.docker.com/r/restic/rest-server
type: application
version: 0.0.1
