annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - GameServers
    - Productivity
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "DESCRIPTION\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/wordle
icon: https://truecharts.org/_static/img/appicons/wordle.png
keywords:
- wordle
- GameServers
- Productivity
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: wordle
sources:
- https://github.com/modem7/docker-wordle
- https://hub.docker.com/r/modem7/wordle
type: application
version: 0.0.1
