annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Downloaders
    - Tools-Utilities
    - MediaApp-Video
    - MediaServer-Video
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "DESCRIPTION\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/youtube-dl
icon: https://truecharts.org/_static/img/appicons/youtube-dl.png
keywords:
- youtube-dl
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: youtube-dl
sources:
- https://github.com/Jeeaaasus/youtube-dl
- https://hub.docker.com/r/jeeaaasustest/youtube-dl/
type: application
version: 0.0.1
