annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A web interface for MySQL and MariaDB.
home: https://github.com/truecharts/apps/tree/master/charts/stable/phpmyadmin
icon: https://truecharts.org/_static/img/appicons/phpmyadmin.png
keywords:
- phpmyadmin
- Tools-Utilities
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: phpmyadmin
sources:
- https://hub.docker.com/r/phpmyadmin/phpmyadmin/
type: application
version: 0.0.1
