annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Downloaders
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "GoAutoYT makes it easy for you to automatically download videos from\
  \ as many YouTube channels as you'd like.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/go-auto-yt
icon: https://truecharts.org/_static/img/appicons/go-auto-yt.png
keywords:
- go-auto-yt
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: go-auto-yt
sources:
- https://github.com/XiovV/go-auto-yt
- https://hub.docker.com/r/xiovv/go-auto-yt
type: application
version: 0.0.1
