annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This Docker will download and install the preferred version of Xonotic.\r\
  \n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/xonotic
icon: https://truecharts.org/_static/img/appicons/xonotic.png
keywords:
- xonotic
- GameServers
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: xonotic
sources:
- https://www.xonotic.org/
- https://hub.docker.com/r/ich777/xonotic/
type: application
version: 0.0.1
