annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Kdenlive(https://kdenlive.org/) is a powerful free and open source cross-platform
  video editing program made by the KDE community. Feature rich and production ready.
home: https://github.com/truecharts/apps/tree/master/charts/stable/kdenlive
icon: https://truecharts.org/_static/img/appicons/kdenlive.png
keywords:
- kdenlive
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: kdenlive
sources:
- https://kdenlive.org/
- https://github.com/orgs/linuxserver/packages/container/package/kdenlive
- https://github.com/linuxserver/docker-kdenlive#readme
type: application
version: 0.0.1
