annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Security
    - Tools-Utilities
    - Network-Web
    - Network-DNS
    - Network-Proxy
    - Network-Management
    - Network-VPN
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "DESCRIPTION\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/WireGuard-Easy
icon: https://truecharts.org/_static/img/appicons/WireGuard-Easy.png
keywords:
- wireguard-easy
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: WireGuard-Easy
sources:
- https://github.com/WeeJeWel/wg-easy
- https://hub.docker.com/r/weejewel/wg-easy
type: application
version: 0.0.1
