annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Network-Other
    - Network-Messenger
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A self-hosted telegram python bot that dumps posts from RSS feeds to
  a telegram chat. This script was created because all the third party services were
  unreliable, slow.
home: https://github.com/truecharts/apps/tree/master/charts/stable/rss-to-telegram
icon: https://truecharts.org/_static/img/appicons/rss-to-telegram.png
keywords:
- rss-to-telegram
- Network-Other
- Network-Messenger
- Productivity
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: rss-to-telegram
sources:
- https://github.com/BoKKeR/RSS-to-Telegram-Bot
- https://hub.docker.com/r/bokker/rss.to.telegram
type: application
version: 0.0.1
