annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Downloaders
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Docker image with qBittorrent and the Flood UI.
home: https://github.com/truecharts/apps/tree/master/charts/stable/qflood
icon: https://truecharts.org/_static/img/appicons/qflood.png
keywords:
- qflood
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: qflood
sources:
- https://hotio.dev/containers/qflood
- https://hub.docker.com/r/hotio/qflood
type: application
version: 0.0.1
