annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "A web interface for managing docker containers with an emphasis on templating\
  \ to provide one-click deployments of dockerized applications. Think of it as a\
  \ decentralized app store for servers that anyone can make packages for.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/yacht
icon: https://truecharts.org/_static/img/appicons/yacht.png
keywords:
- yacht
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: yacht
sources:
- https://github.com/SelfhostedPro/Yacht
- https://hub.docker.com/r/selfhostedpro/yacht
type: application
version: 0.0.1
