annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Ubuntu 20.04 (LTS), XFCE-Desktop, noVNC, LibreOffice, Firefox\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/ubuntu-xfce
icon: https://truecharts.org/_static/img/appicons/ubuntu-xfce.png
keywords:
- ubuntu-xfce
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: ubuntu-xfce
sources:
- https://hub.docker.com/r/knilix/ubuntu-xfce-vnc-novnc
type: application
version: 0.0.1
