annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: '[b]FTB Presents Skyfactory 3[/b][br]It''s skyblock like you''ve never
  seen it before! High tech mods and full automation![br][br]Setup:[br][li]You must
  accept the EULA by setting the [b]EULA[/b] variable to [span style=''color: #00E800;'']true[/span]
  or the install will fail.[br]Optional:[br][li]You can setup a comma separated list
  of players who will have admin privileges in game by setting [b]OPS[/b]'
home: https://github.com/truecharts/apps/tree/master/charts/stable/skyfactory3
icon: https://truecharts.org/_static/img/appicons/skyfactory3.png
keywords:
- skyfactory3
- GameServers
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: skyfactory3
sources:
- https://feed-the-beast.com/modpack/ftb_presents_skyfactory_3
- https://hub.docker.com/repository/docker/goobaroo/ftbskyfactory3
type: application
version: 0.0.1
