annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - HomeAutomation
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Configurable WyzeSense to MQTT Gateway for Home Assistant.  Refer to
  the WyzeSense2MQTT docs for configuration. Change your hidraw port to pass into
  the container as necessary.
home: https://github.com/truecharts/apps/tree/master/charts/stable/wyzesense2mqtt
icon: https://truecharts.org/_static/img/appicons/wyzesense2mqtt.png
keywords:
- wyzesense2mqtt
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: wyzesense2mqtt
sources:
- https://hub.docker.com/r/raetha/wyzesense2mqtt/
type: application
version: 0.0.1
