annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'You need to run ZcashSwingWallet on the desktop to open the wallet&#xD;

  '
home: https://github.com/truecharts/apps/tree/master/charts/stable/zcashwalletgui
icon: https://truecharts.org/_static/img/appicons/zcashwalletgui.png
keywords:
- zcashwalletgui
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: zcashwalletgui
sources:
- https://hub.docker.com/r/ulisses1478/zcashwallet
type: application
version: 0.0.1
