annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - MediaApp-Video
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Neko is an Open-Source self-hosted Alternative to rabb.it(deprecated).\r\
  \n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/neko
icon: https://truecharts.org/_static/img/appicons/neko.png
keywords:
- neko
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: neko
sources:
- https://hub.docker.com/r/m1k1o/neko/
type: application
version: 0.0.1
