annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Cloud
    - MediaApp-Video
    - MediaApp-Music
    - MediaApp-Photos
    - MediaServer-Video
    - MediaServer-Music
    - MediaServer-Photos
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Homepage: http://bpatrik.github.io/pigallery2/\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/pigallery2
icon: https://truecharts.org/_static/img/appicons/pigallery2.png
keywords:
- pigallery2
- Cloud
- MediaApp-Video
- MediaApp-Music
- MediaApp-Photos
- MediaServer-Video
- MediaServer-Music
- MediaServer-Photos
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: pigallery2
sources:
- https://github.com/bpatrik/pigallery2
- https://hub.docker.com/r/bpatrik/pigallery2
type: application
version: 0.0.1
