annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Network
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This is a Basic STUN &amp; TURN server that was mainly created for Nextcloud\
  \ Talk.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/stun-turn-server
icon: https://truecharts.org/_static/img/appicons/stun-turn-server.png
keywords:
- stun-turn-server
- Network
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: stun-turn-server
sources:
- https://hub.docker.com/r/ich777/stun-turn-server
type: application
version: 0.0.1
