annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - MediaApp-Photos
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'MediaGoblin is a free software media publishing platform that anyone
  can run. You can think of it as a decentralized alternative to Flickr, YouTube,
  SoundCloud, etc. [br][br][b][u][span style=''color: #ff9900;'']Default user/password[/span][/u][/b][br]User:
  [B][u]admin[/B][/u][br]Password: [B][u]admin[/B][/u][/b]'
home: https://github.com/truecharts/apps/tree/master/charts/stable/mediagoblin
icon: https://truecharts.org/_static/img/appicons/mediagoblin.png
keywords:
- mediagoblin
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: mediagoblin
sources:
- https://mediagoblin.org/
- https://hub.docker.com/r/mtlynch/mediagoblin/
type: application
version: 0.0.1
