annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Network-Management
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This is an all-in-one Alpine Linux based Docker image for running the\
  \ Ubiquiti Network Management System. This image contains all the components required\
  \ to run UNMS in a single container and uses the s6-overlay for process management.\r\
  \n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/unms
icon: https://truecharts.org/_static/img/appicons/unms.png
keywords:
- unms
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: unms
sources:
- https://hub.docker.com/r/nico640/docker-unms
type: application
version: 0.0.1
