annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Backup
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Automatically backup github repositories on schedule. Allows for custom
  configuration.
home: https://github.com/truecharts/apps/tree/master/charts/stable/llalon-github-backup
icon: https://truecharts.org/_static/img/appicons/llalon-github-backup.png
keywords:
- llalon-github-backup
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: llalon-github-backup
sources:
- https://github.com/abusesa/github-backup
- https://hub.docker.com/r/llalon/github-backup
type: application
version: 0.0.1
