annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Network-Messenger
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Creates a simple webpage for Slack invite signups
home: https://github.com/truecharts/apps/tree/master/charts/stable/slack-invite
icon: https://truecharts.org/_static/img/appicons/slack-invite.png
keywords:
- slack-invite
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: slack-invite
sources:
- httpss://github.com/ninthwalker/slack-invite
- https://hub.docker.com/r/ninthwalker/slack-invite/
type: application
version: 0.0.1
