annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This Docker will download and install SteamCMD. It will also install\
  \ Killing Floor and run it.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/killingfloor
icon: https://truecharts.org/_static/img/appicons/killingfloor.png
keywords:
- killingfloor
- GameServers
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: killingfloor
sources:
- https://www.tripwireinteractive.com/
- https://hub.docker.com/r/ich777/steamcmd/
type: application
version: 0.0.1
