annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Network-DNS
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'Unbound is a validating, recursive, and caching DNS resolver.  It can
  be used to create your own recursive DNS-Server at home. You can use Unbound for
  services such as Pi-Hole (Here is a tutorial how to configure Pi-Hole with Unbound:
  https://www.youtube.com/watch?v=FnFtWsZ8IP0&amp;t=695s) or you can create custom
  DNS Records for your local network.'
home: https://github.com/truecharts/apps/tree/master/charts/stable/unbound
icon: https://truecharts.org/_static/img/appicons/unbound.png
keywords:
- unbound
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: unbound
sources:
- https://github.com/kutzilla/unbound-docker
- https://hub.docker.com/r/kutzilla/unbound
type: application
version: 0.0.1
