annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Webtop(https://github.com/linuxserver/gclient) - Alpine, Ubuntu, Fedora,
  and Arch based containers containing full desktop environments in officially supported
  flavors accessible via any modern web browser.
home: https://github.com/truecharts/apps/tree/master/charts/stable/webtop
icon: https://truecharts.org/_static/img/appicons/webtop.png
keywords:
- webtop
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: webtop
sources:
- https://github.com/linuxserver/gclient
- https://github.com/orgs/linuxserver/packages/container/package/webtop
type: application
version: 0.0.1
