annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Simple access to Metabase through a Docker container. Metabase is the
  easy, open source way for everyone in your company to ask questions and learn from
  data.
home: https://github.com/truecharts/apps/tree/master/charts/stable/metabase
icon: https://truecharts.org/_static/img/appicons/metabase.png
keywords:
- metabase
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: metabase
sources:
- https://hub.docker.com/r/metabase/metabase/
type: application
version: 0.0.1
