annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "wger (\u02C8v\u025B\u0261\u0250) Workout Manager is a free, open source\
  \ web\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/wger-unraid
icon: https://truecharts.org/_static/img/appicons/wger-unraid.png
keywords:
- wger-unraid
- Productivity
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: wger-unraid
sources:
- https://wger.de/software/features
- https://registry.hub.docker.com/r/wger/devel
type: application
version: 0.0.1
