annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "DESCRIPTION\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/mayan-edms
icon: https://truecharts.org/_static/img/appicons/mayan-edms.png
keywords:
- mayan-edms
- Productivity
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: mayan-edms
sources:
- https://github.com/elancapital/mayan-edms-docker
- https://hub.docker.com/r/mayanedms/mayanedms
type: application
version: 0.0.1
