annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: The leading open source automation server, Jenkins provides hundreds
  of plugins to support building, deploying and automating any project.
home: https://github.com/truecharts/apps/tree/master/charts/stable/jenkins
icon: https://truecharts.org/_static/img/appicons/jenkins.png
keywords:
- jenkins
- Productivity
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: jenkins
sources:
- https://www.jenkins.io/
- https://hub.docker.com/r/jenkins/jenkins/
type: application
version: 0.0.1
