annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools-Utilities
    - Network-Web
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "YaCy decentralized search engine (https://yacy.net)[br][br][b][u][span\
  \ style='color: #ff9900;']Default user/password[/span][/u][/b][br]User: [B][u]admin[/B][/u][br]Password:\
  \ [B][u]yacy[/B][/u][/b]\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/yacy
icon: https://truecharts.org/_static/img/appicons/yacy.png
keywords:
- yacy
- Tools-Utilities
- Network-Web
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: yacy
sources:
- https://yacy.net/
- https://hub.docker.com/r/yacy/yacy_search_server/
type: application
version: 0.0.1
