annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - HomeAutomation
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Node-RED is a visual tool for wiring the Internet of Things[br][br]\r\
  \n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/noderedv2beta
icon: https://truecharts.org/_static/img/appicons/noderedv2beta.png
keywords:
- noderedv2beta
- HomeAutomation
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: noderedv2beta
sources:
- https://nodered.org
- https://hub.docker.com/r/nodered/node-red-dev/
type: application
version: 0.0.1
