annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Trilium Notes is a hierarchical note taking application with focus on\
  \ building large personal knowledge bases.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/trilium
icon: https://truecharts.org/_static/img/appicons/trilium.png
keywords:
- trilium
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: trilium
sources:
- https://github.com/zadam/trilium
- https://hub.docker.com/r/zadam/trilium
type: application
version: 0.0.1
