annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Monitor your game servers on Discord and tracks the live data of your\
  \ game servers.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/discord-gameservermonitor
icon: https://truecharts.org/_static/img/appicons/discord-gameservermonitor.png
keywords:
- discord-gameservermonitor
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: discord-gameservermonitor
sources:
- https://discordgsm.com/
- https://hub.docker.com/r/joey291/discordgsm
type: application
version: 0.0.1
