annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
    - Network-Management
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This is a Dockerfile for Splunk designed for OpenShift and unRAID based\
  \ on Alpine Linux - https://www.splunk.com\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/splunk
icon: https://truecharts.org/_static/img/appicons/splunk.png
keywords:
- splunk
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: splunk
sources:
- https://www.splunk.com/
- https://hub.docker.com/r/atunnecliffe/splunk
type: application
version: 0.0.1
