annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - MediaApp-Photos
    - MediaServer-Photos
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: '*BETA* Fotosho is a photo gallery for your home server. Organize your
  photos into albums internally and view as a slideshow. Free and open source. Does
  not require a database. Does not move, copy or modify your photos.'
home: https://github.com/truecharts/apps/tree/master/charts/stable/fotosho
icon: https://truecharts.org/_static/img/appicons/fotosho.png
keywords:
- fotosho
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: fotosho
sources:
- https://github.com/advplyr/fotosho
- https://hub.docker.com/r/advplyr/fotosho/
type: application
version: 0.0.1
