annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This takes ESPN+ and transforms it into a \"live TV\" experience with\
  \ virtual linear channels. It will discover what is on, and generate a schedule\
  \ of channels that will give you M3U and XMLTV files that you can import into something\
  \ like Jellyfin or VLC.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/eplustv
icon: https://truecharts.org/_static/img/appicons/eplustv.png
keywords:
- eplustv
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: eplustv
sources:
- https://hub.docker.com/r/m0ngr31/eplustv/
type: application
version: 0.0.1
