annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Tools-Utilities
    - MediaApp-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A website-based platform and API for collecting Plex user stats within
  a set timeframe using Tautulli. The data is displayed as a stat-summary, sort of
  like Spotify Wrapped. Yes, you need Tautulli to have been running beforehand and
  currently for this to work.
home: https://github.com/truecharts/apps/tree/master/charts/stable/wrapperr
icon: https://truecharts.org/_static/img/appicons/wrapperr.png
keywords:
- wrapperr
- Productivity
- Tools-Utilities
- MediaApp-Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: wrapperr
sources:
- https://github.com/aunefyren/wrapperr
- https://hub.docker.com/r/aunefyren/wrapperr
type: application
version: 0.0.1
