annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Backup
    - MediaApp-Video
    - MediaApp-Music
    - MediaApp-Other
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: This container will detect optical disks by their type and rip them automatically.
home: https://github.com/truecharts/apps/tree/master/charts/stable/ripper
icon: https://truecharts.org/_static/img/appicons/ripper.png
keywords:
- ripper
- Backup
- MediaApp-Video
- MediaApp-Music
- MediaApp-Other
- Productivity
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: ripper
sources:
- https://registry.hub.docker.com/r/rix1337/docker-ripper
- https://github.com/rix1337/docker-ripper#readme
type: application
version: 0.0.1
