annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Tools-Utilities
    - Network-Web
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "An Instant App &amp; API for your SQL Database.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/directus
icon: https://truecharts.org/_static/img/appicons/directus.png
keywords:
- directus
- Productivity
- Tools-Utilities
- Network-Web
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: directus
sources:
- https://github.com/directus/directus
- https://hub.docker.com/r/directus/directus/
type: application
version: 0.0.1
