annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Backup
    - Downloaders
    - MediaApp-Video
    - MediaApp-Music
    - MediaApp-Photos
    - MediaApp-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: DEVELOPMENT BUILD - Latest changes are made here! Tired of searching
  for media on different torrent websites or paying for Usenet server access? Well
  look no further! You can now use PlexRipper to download "everything" from the Plex
  servers you have access to and expand your collection that way! Let others collect
  media for you and then just download everything!
home: https://github.com/truecharts/apps/tree/master/charts/stable/plexripper-development
icon: https://truecharts.org/_static/img/appicons/plexripper-development.png
keywords:
- plexripper-development
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: plexripper-development
sources:
- https://github.com/PlexRipper/PlexRipper/
- https://hub.docker.com/r/plexripper/plexripper/
type: application
version: 0.0.1
