annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This application will allow you to sort films and series. It will clean\
  \ up the names and move them to the folder you want.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/search-and-sort-movies
icon: https://truecharts.org/_static/img/appicons/search-and-sort-movies.png
keywords:
- search-and-sort-movies
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: search-and-sort-movies
sources:
- https://hub.docker.com/r/olprog/search-and-sort-movies/
type: application
version: 0.0.1
