annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Tools-Utilities
    - Network-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Self-hosted monitoring tool like \"Uptime Robot\".  \r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/uptimekuma
icon: https://truecharts.org/_static/img/appicons/uptimekuma.png
keywords:
- uptimekuma
- Productivity
- Tools-Utilities
- Network-Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: uptimekuma
sources:
- https://github.com/louislam/uptime-kuma
- https://hub.docker.com/r/louislam/uptime-kuma/
type: application
version: 0.0.1
