annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A lightweight, self-hosted paste platform (Pastebin alternative) with
  language detection and on-disk encryption.
home: https://github.com/truecharts/apps/tree/master/charts/stable/Pastey
icon: https://truecharts.org/_static/img/appicons/Pastey.png
keywords:
- pastey
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: Pastey
sources:
- https://github.com/Cesura/pastey
- https://hub.docker.com/r/cesura/pastey/
type: application
version: 0.0.1
