annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Security
    - Network-Proxy
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Shadowsocks is a tunneling proxy developed to be free, open-source,\
  \ and mainly used by Chinese people to bypass the Great Firewall restrictions. While\
  \ using, it covers your browser traffic only, and it is almost impossible to detect\
  \ and block it.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/shadowsocks-server
icon: https://truecharts.org/_static/img/appicons/shadowsocks-server.png
keywords:
- shadowsocks-server
- Security
- Network-Proxy
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: shadowsocks-server
sources:
- https://github.com/qdm12/ss-server
- https://hub.docker.com/r/qmcgaw/ss-server
type: application
version: 0.0.1
