annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "A safe and private place for your life's work.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/standardnotes-web
icon: https://truecharts.org/_static/img/appicons/standardnotes-web.png
keywords:
- standardnotes-web
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: standardnotes-web
sources:
- https://standardnotes.org/
- https://hub.docker.com/r/standardnotes/web
type: application
version: 0.0.1
