annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Tagbox lets you identify the content of images by getting a list of ordered
  tags.
home: https://github.com/truecharts/apps/tree/master/charts/stable/machinebox-tagbox
icon: https://truecharts.org/_static/img/appicons/machinebox-tagbox.png
keywords:
- machinebox-tagbox
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: machinebox-tagbox
sources:
- https://machinebox.io/docs/tagbox
- https://hub.docker.com/r/machinebox/tagbox
type: application
version: 0.0.1
