annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Network-Web
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: An open source alternative front-end to YouTube
home: https://github.com/truecharts/apps/tree/master/charts/stable/invidious
icon: https://truecharts.org/_static/img/appicons/invidious.png
keywords:
- invidious
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: invidious
sources:
- https://github.com/iv-org/invidious
- https://quay.io/repository/invidious/invidious
type: application
version: 0.0.1
