annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Cloud
    - Tools-Utilities
    - Network-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "DESCRIPTION\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/vlmcsd-kms-server
icon: https://truecharts.org/_static/img/appicons/vlmcsd-kms-server.png
keywords:
- vlmcsd-kms-server
- Cloud
- Tools-Utilities
- Network-Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: vlmcsd-kms-server
sources:
- https://github.com/mikolatero/docker-vlmcsd
- https://hub.docker.com/r/mikolatero/vlmcsd/
type: application
version: 0.0.1
