annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "***NOTE*** First run is slow.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/rstudio
icon: https://truecharts.org/_static/img/appicons/rstudio.png
keywords:
- rstudio
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: rstudio
sources:
- https://github.com/rocker-org/rocker-versioned
- https://hub.docker.com/r/rocker/rstudio/
type: application
version: 0.0.1
