annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Network-Other
    - Productivity
    - Tools-Utilities
    - Backup
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "MEGAsync is an intuitive application that enables you to effortlessly\
  \ synchronize folders on several computers. You simply need to upload data in the\
  \ cloud and, within seconds, you can explore the same documents on your own PC.\r\
  \n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/megasync
icon: https://truecharts.org/_static/img/appicons/megasync.png
keywords:
- megasync
- Network-Other
- Productivity
- Tools-Utilities
- Backup
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: megasync
sources:
- https://hub.docker.com/r/ich777/doh-server
- https://hub.docker.com/r/ich777/megasync
type: application
version: 0.0.1
