annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Self hosted note taking, alternative to Notions. Look at Github for config
home: https://github.com/truecharts/apps/tree/master/charts/stable/notea
icon: https://truecharts.org/_static/img/appicons/notea.png
keywords:
- notea
- Productivity
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: notea
sources:
- https://github.com/diamkil/docker-notea
- https://registry.hub.docker.com/r/diamkil/notea/
type: application
version: 0.0.1
