annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Backup
    - GameServers
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "An all in one lancache docker providing a combination of the following\
  \ three projects:\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/lancache-bundle
icon: https://truecharts.org/_static/img/appicons/lancache-bundle.png
keywords:
- lancache-bundle
- Backup
- GameServers
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: lancache-bundle
sources:
- https://github.com/Josh5/lancache-bundle
- https://hub.docker.com/repository/docker/josh5/lancache-bundle
type: application
version: 0.0.1
