annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This Docker will download and install SteamCMD. It will also install\
  \ The Forest and run it. SERVERNAME: 'The Forest Docker' SERVERPASSWORD: 'Docker'\
  \ ADMINPASSWORD: 'adminDocker' (you can change this in your SERVERFOLDER/config/config.cfg)\r\
  \n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/theforest
icon: https://truecharts.org/_static/img/appicons/theforest.png
keywords:
- theforest
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: theforest
sources:
- https://www.steampowered.com/
- https://hub.docker.com/r/ich777/steamcmd/
type: application
version: 0.0.1
