annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Searx is a free internet metasearch engine which aggregates results from
  more than 70 search services. Users are neither tracked nor profiled. Additionally,
  searx can be used over Tor for online anonymity.
home: https://github.com/truecharts/apps/tree/master/charts/stable/searx
icon: https://truecharts.org/_static/img/appicons/searx.png
keywords:
- searx
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: searx
sources:
- https://github.com/asciimoo/searx
- https://hub.docker.com/r/searx/searx/
type: application
version: 0.0.1
