annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
    - Network-Management
    - Network-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This tool will continuosly run Speedtests at the chosen interval and\
  \ export the data to InfluxDB. &lt;br&gt;\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/speedflux
icon: https://truecharts.org/_static/img/appicons/speedflux.png
keywords:
- speedflux
- Tools-Utilities
- Network-Management
- Network-Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: speedflux
sources:
- https://github.com/breadlysm/speedtest-to-influxdb
- https://github.com/users/breadlysm/packages/container/package/speedflux
type: application
version: 0.0.1
