annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Cloud
    - Network-Web
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Proxy is in quotes because I couldn't think of a better name. There\
  \ is nothing overly special about this other than using it as a simple and easy\
  \ to use dashboard for all your self-hosted services.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/jmzhomeproxy
icon: https://truecharts.org/_static/img/appicons/jmzhomeproxy.png
keywords:
- jmzhomeproxy
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: jmzhomeproxy
sources:
- https://github.com/JmzTaylor/homelab_proxy/
- https://hub.docker.com/u/jmzsoftware
type: application
version: 0.0.1
