annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "farmOS is a web-based application for farm management, planning, and\
  \ record keeping. It is developed by a community of volunteers and aims to provide\
  \ a standard platform for farmers, developers, and researchers to build upon.\r"
home: https://github.com/truecharts/apps/tree/master/charts/stable/farmos
icon: https://truecharts.org/_static/img/appicons/farmos.png
keywords:
- farmos
- Productivity
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: farmos
sources:
- https://github.com/farmOS/farmOS
- https://hub.docker.com/r/farmos/farmos/
type: application
version: 0.0.1
