annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'The Ravencoin project is launched based on the hard work and continuous
  effort of over 400 Bitcoin developers who made over 14,000 commits over the life
  to date of the Bitcoin project.

  '
home: https://github.com/truecharts/apps/tree/master/charts/stable/RavencoinP2P
icon: https://truecharts.org/_static/img/appicons/RavencoinP2P.png
keywords:
- ravencoinp2p
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: RavencoinP2P
sources:
- https://github.com/RavenProject/Ravencoin
- https://hub.docker.com/r/angelics/unraid-docker-ravencoin-p2p
type: application
version: 0.0.1
