annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Cloud
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Simple open source self-hosted file sharing solution.[br] To access Admin
  Page add /admin at the end of the URL[/br]
home: https://github.com/truecharts/apps/tree/master/charts/stable/psitransfer
icon: https://truecharts.org/_static/img/appicons/psitransfer.png
keywords:
- psitransfer
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: psitransfer
sources:
- https://github.com/psi-4ward/psitransfer
- https://hub.docker.com/r/psitrax/psitransfer/
type: application
version: 0.0.1
