annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: 'RSS search an notification.

  '
home: https://github.com/truecharts/apps/tree/master/charts/stable/rssnotipy
icon: https://truecharts.org/_static/img/appicons/rssnotipy.png
keywords:
- rssnotipy
- Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: rssnotipy
sources:
- https://github.com/maschhoff/RSSNotipy
- https://hub.docker.com/repository/docker/knex666/rssnotipy
type: application
version: 0.0.1
