annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - MediaServer-Video
    - MediaServer-Music
    - MediaServer-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: TwonkyMedia server (TMS) is DLNA-compliant UPnP AV server software from
  PacketVideo. TwonkyMedia server can be used to share and stream media to most UPnP
  AV or DLNA-compliant clients, in addition to non-UPnP devices through the HTML,
  RSS, and JSON supported front ends.
home: https://github.com/truecharts/apps/tree/master/charts/stable/twonky-server
icon: https://truecharts.org/_static/img/appicons/twonky-server.png
keywords:
- twonky-server
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: twonky-server
sources:
- https://github.com/H2CK/twonkyserver
- https://hub.docker.com/r/dtjs48jkt/twonkyserver/
type: application
version: 0.0.1
