annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools
    - MediaApp-Video
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Mediaelch is a Tool to manage your movie and show libary regarding the
  metadata and artwork.
home: https://github.com/truecharts/apps/tree/master/charts/stable/mediaelch
icon: https://truecharts.org/_static/img/appicons/mediaelch.png
keywords:
- mediaelch
- Tools
- MediaApp-Video
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: mediaelch
sources:
- https://github.com/Komet/MediaElch
- https://hub.docker.com/repository/docker/masonxx/mediaelch
type: application
version: 0.0.1
