annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - GameServers
    - Productivity
    - MediaApp-Video
    - MediaServer-Video
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This container is based on bb12489/gui-docker &amp;amp;amp; bb12489/docker-obs.\
  \ The OBS with NDI is incorporated into the container and can be used to stream\
  \ your desktop. The main reason for this fork is to update the container and add\
  \ it to the unraid app store.&amp;#xD;\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/obs-ndi
icon: https://truecharts.org/_static/img/appicons/obs-ndi.png
keywords:
- obs-ndi
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: obs-ndi
sources:
- https://github.com/patrickstigler/docker-obs-ndi
- https://hub.docker.com/r/patrickstigler/obs-ndi
type: application
version: 0.0.1
