annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Cloud
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Tonido Server allows you to access all your files on your computer from
  a web browser, smartphone, tablet or even DLNA enabled devices. No setup necessary.
home: https://github.com/truecharts/apps/tree/master/charts/stable/tonido
icon: https://truecharts.org/_static/img/appicons/tonido.png
keywords:
- tonido
- Cloud
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: tonido
sources:
- https://registry.hub.docker.com/r/captinsano/tonido/
type: application
version: 0.0.1
