annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Backup
    - Network-DNS
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "FOG Project can capture, deploy, and manage Windows, Mac OSX, and various\
  \ Linux distributions.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/fogproject
icon: https://truecharts.org/_static/img/appicons/fogproject.png
keywords:
- fogproject
- Backup
- Network-DNS
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: fogproject
sources:
- https://github.com/redvex2460/fogproject
type: application
version: 0.0.1
