annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - HomeAutomation
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Home Assistant online configurator container from https://github.com/danielperna84/hass-configurator
home: https://github.com/truecharts/apps/tree/master/charts/stable/hassconfigurator
icon: https://truecharts.org/_static/img/appicons/hassconfigurator.png
keywords:
- hassconfigurator
- HomeAutomation
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: hassconfigurator
sources:
- https://github.com/danielperna84/hass-configurator
- https://hub.docker.com/r/causticlab/hass-configurator-docker//Dockerfile/
type: application
version: 0.0.1
