annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Tools-Utilities
    - Security
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: OpenVAS is a full-featured vulnerability scanner. Its capabilities include
  unauthenticated testing, authenticated testing, various high level and low level
  Internet and industrial protocols, performance tuning for large-scale scans and
  a powerful internal programming language to implement any type of vulnerability
  test.
home: https://github.com/truecharts/apps/tree/master/charts/stable/frak-gvm
icon: https://truecharts.org/_static/img/appicons/frak-gvm.png
keywords:
- frak-gvm
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: frak-gvm
sources:
- https://www.openvas.org/
- https://registry.hub.docker.com/r/securecompliance/gvm/
type: application
version: 0.0.1
