annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Logarr is a self-hosted, single-page, log consolidation tool written
  in PHP
home: https://github.com/truecharts/apps/tree/master/charts/stable/logarr
icon: https://truecharts.org/_static/img/appicons/logarr.png
keywords:
- logarr
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: logarr
sources:
- https://github.com/Monitorr/logarr/
- https://hub.docker.com/r/monitorr/logarr-alpha/
type: application
version: 0.0.1
