annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Network-Messenger
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Limnoria(https://github.com/ProgVal/limnoria) A robust, full-featured,
  and user/programmer-friendly Python IRC bot, with many existing plugins. Successor
  of the well-known Supybot.
home: https://github.com/truecharts/apps/tree/master/charts/stable/limnoria
icon: https://truecharts.org/_static/img/appicons/limnoria.png
keywords:
- limnoria
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: limnoria
sources:
- https://github.com/ProgVal/limnoria
- https://github.com/orgs/linuxserver/packages/container/package/limnoria
type: application
version: 0.0.1
