annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Downloaders
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "a xml grabber from schedule direct service\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/guide2go
icon: https://truecharts.org/_static/img/appicons/guide2go.png
keywords:
- guide2go
- Downloaders
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: guide2go
sources:
- https://github.com/alturismo/guide2go
- https://hub.docker.com/r/alturismo/guide2go
type: application
version: 0.0.1
