annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Downloaders
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Docker image with rTorrent and the Flood UI.
home: https://github.com/truecharts/apps/tree/master/charts/stable/rflood
icon: https://truecharts.org/_static/img/appicons/rflood.png
keywords:
- rflood
- Downloaders
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: rflood
sources:
- https://hotio.dev/containers/rflood
- https://hub.docker.com/r/hotio/rflood
type: application
version: 0.0.1
