annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Network-Management
    - Network-VPN
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Tailscale is a zero config VPN for building secure networks.
home: https://github.com/truecharts/apps/tree/master/charts/stable/tailscaleclient
icon: https://truecharts.org/_static/img/appicons/tailscaleclient.png
keywords:
- tailscaleclient
- Network-Management
- Network-VPN
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: tailscaleclient
sources:
- https://tailscale.com/
- https://hub.docker.com/repository/docker/hussainalhaddad/tailscale
type: application
version: 0.0.1
