annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - MediaServer-Video
    - MediaServer-Music
    - MediaServer-Books
    - MediaServer-Photos
    - MediaServer-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A modern web client for Jellyfin based on Vue. It relies on Jellyfin
  to store and manage your media. This version uses server side rendering for improved
  performance.
home: https://github.com/truecharts/apps/tree/master/charts/stable/Jellyfin-vue-ssr
icon: https://truecharts.org/_static/img/appicons/Jellyfin-vue-ssr.png
keywords:
- jellyfin-vue-ssr
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: Jellyfin-vue-ssr
sources:
- https://jellyfin.org
- https://hub.docker.com/r/jellyfin/jellyfin-vue
type: application
version: 0.0.1
