annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Network-Web
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: HumHub is a free social network software and framework built to give
  you the tools to make communication and collaboration easy and successful. The Database
  is at 'localhost', username is 'humhub', the database name is 'humhub', there are
  no password (local user)
home: https://github.com/truecharts/apps/tree/master/charts/stable/humhub
icon: https://truecharts.org/_static/img/appicons/humhub.png
keywords:
- humhub
- Network-Web
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: humhub
sources:
- https://ghcr.io/siwatinc/humhub
type: application
version: 0.0.1
