annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "SonarQube is an open source platform for continuous inspection of code\
  \ quality.   \r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/SonarQube
icon: https://truecharts.org/_static/img/appicons/SonarQube.png
keywords:
- sonarqube
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: SonarQube
sources:
- https://github.com/SonarSource/sonarqube
- https://hub.docker.com/_/sonarqube/
type: application
version: 0.0.1
