annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: The to-do app to organize your life.
home: https://github.com/truecharts/apps/tree/master/charts/stable/vikunja-frontend
icon: https://truecharts.org/_static/img/appicons/vikunja-frontend.png
keywords:
- vikunja-frontend
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: vikunja-frontend
sources:
- https://vikunja.io/
- https://hub.docker.com/r/vikunja/frontend/
type: application
version: 0.0.1
