annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - GameServers
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "A tool for managing Factorio servers \r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/FactorioServerManager
icon: https://truecharts.org/_static/img/appicons/FactorioServerManager.png
keywords:
- factorioservermanager
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: FactorioServerManager
sources:
- https://github.com/OpenFactorioServerManager/factorio-server-manager
- https://hub.docker.com/r/ofsm/ofsm
type: application
version: 0.0.1
