annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Network-Other
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Enpass is a cross-platform password management app to securely store\
  \ passwords and other credentials in a virtual vault locked with a master password.\r\
  \n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/enpass
icon: https://truecharts.org/_static/img/appicons/enpass.png
keywords:
- enpass
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: enpass
sources:
- https://www.enpass.io/
- https://hub.docker.com/r/ich777/enpass
type: application
version: 0.0.1
