annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Network-DNS
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "A very simple DNS server to connect to DNS-over-HTTPS service. This\
  \ is similar to my other Pihole-with-DoH docker, without Pihole.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/dns-doh-companion
icon: https://truecharts.org/_static/img/appicons/dns-doh-companion.png
keywords:
- dns-doh-companion
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: dns-doh-companion
sources:
- https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/
- https://hub.docker.com/r/testdasi/simple-dns-doh/
type: application
version: 0.0.1
