annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - MediaServer-Music
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Self-hosted music scrobble database to create personal listening statistics\
  \ and charts as a substitute for Last.fm / Libre.fm / GNU FM.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/maloja
icon: https://truecharts.org/_static/img/appicons/maloja.png
keywords:
- maloja
- MediaServer-Music
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: maloja
sources:
- https://maloja.krateng.ch/
- https://hub.docker.com/r/krateng/maloja
type: application
version: 0.0.1
