annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Fenrus is a home page / personal dashboard with smart apps.   \n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/fenrus
icon: https://truecharts.org/_static/img/appicons/fenrus.png
keywords:
- fenrus
- Productivity
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: fenrus
sources:
- http://fenrus.io
- https://hub.docker.com/r/revenz/fenrus/
type: application
version: 0.0.1
