annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Downloaders
    - MediaApp-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: This tool will help manage tedious tasks in qBittorrent and automate
  them. Tag, categorize, remove orphaned data, remove unregistered torrents and much
  much more.
home: https://github.com/truecharts/apps/tree/master/charts/stable/qbitmanage
icon: https://truecharts.org/_static/img/appicons/qbitmanage.png
keywords:
- qbitmanage
- Downloaders
- MediaApp-Other
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: qbitmanage
sources:
- https://hotio.dev/containers/qbitmanage
- https://hub.docker.com/r/hotio/qbitmanage
type: application
version: 0.0.1
