annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - HomeAutomation
    - Network-Other
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Xeoma is surveillance software. Connect your cameras and record any detected
  movement.
home: https://github.com/truecharts/apps/tree/master/charts/stable/xeoma
icon: https://truecharts.org/_static/img/appicons/xeoma.png
keywords:
- xeoma
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: xeoma
sources:
- http://felenasoft.com/xeoma/
- https://hub.docker.com/r/coppit/xeoma/
type: application
version: 0.0.1
