annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Network-Web
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A web client for Reddit
home: https://github.com/truecharts/apps/tree/master/charts/stable/troddit
icon: https://truecharts.org/_static/img/appicons/troddit.png
keywords:
- troddit
- Network-Web
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: troddit
sources:
- https://github.com/burhan-syed/troddit
- https://hub.docker.com/r/bsyed/troddit
type: application
version: 0.0.1
