annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Automatically login, bypass Captchas, and redeem free games.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/epicgames-freegames
icon: https://truecharts.org/_static/img/appicons/epicgames-freegames.png
keywords:
- epicgames-freegames
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: epicgames-freegames
sources:
- https://github.com/claabs/epicgames-freegames-node
- https://hub.docker.com/r/charlocharlie/epicgames-freegames/
type: application
version: 0.0.1
