annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Cloud
    - Productivity
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: gogs https://gogs.io/ is a painless self-hosted Git service [br][br]
home: https://github.com/truecharts/apps/tree/master/charts/stable/gogs
icon: https://truecharts.org/_static/img/appicons/gogs.png
keywords:
- gogs
- Cloud
- Productivity
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: gogs
sources:
- https://hub.docker.com/r/gogs/gogs/
type: application
version: 0.0.1
