annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - MediaApp-Photos
    - MediaServer-Video
    - MediaServer-Photos
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: '[b]PhotoStructure is your new home for all your photos and videos.[/b]

  '
home: https://github.com/truecharts/apps/tree/master/charts/stable/PhotoStructure
icon: https://truecharts.org/_static/img/appicons/PhotoStructure.png
keywords:
- photostructure
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: PhotoStructure
sources:
- https://photostructure.com/
- https://hub.docker.com/r/photostructure/server/
type: application
version: 0.0.1
