annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Productivity
    - Tools-Utilities
    - MediaApp-Video
    - MediaApp-Music
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "DESCRIPTION\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/tartube
icon: https://truecharts.org/_static/img/appicons/tartube.png
keywords:
- tartube
- Productivity
- Tools-Utilities
- MediaApp-Video
- MediaApp-Music
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: tartube
sources:
- https://github.com/axcore/tartube
- https://hub.docker.com/r/468654/tartube
type: application
version: 0.0.1
