annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Crypto
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: Simple container for displaying stats from any PhoenixMiner instance.
  Made to go with PhoenixMiner-AMD.
home: https://github.com/truecharts/apps/tree/master/charts/stable/phoenixstats
icon: https://truecharts.org/_static/img/appicons/phoenixstats.png
keywords:
- phoenixstats
- Crypto
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: phoenixstats
sources:
- https://hub.docker.com/r/lnxd/phoenixstats
type: application
version: 0.0.1
