annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools-Utilities
    - MediaApp-Video
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "Mobile friendly tool for downloading videos from social media.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/media-roller
icon: https://truecharts.org/_static/img/appicons/media-roller.png
keywords:
- media-roller
- Tools-Utilities
- MediaApp-Video
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: media-roller
sources:
- https://github.com/rroller/media-roller
- https://hub.docker.com/repository/docker/ronnieroller/media-roller
type: application
version: 0.0.1
