annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: | 
    - Productivity
    - Tools-Utilities
    - Network-Web
    - Network-Management
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "DESCRIPTION\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/keeweb
icon: https://truecharts.org/_static/img/appicons/keeweb.png
keywords:
- keeweb
- Productivity
- Tools-Utilities
- Network-Web
- Network-Management
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: keeweb
sources:
- https://github.com/keeweb/keeweb
- https://hub.docker.com/r/antelle/keeweb
type: application
version: 0.0.1
