annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: &id001
    - Backup
    - Cloud
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: "This application backs up every folder mounted at `/data/` to a given\
  \ AWS S3 path using the `aws s3 sync` command. It requires a pair of (IAM) Access\
  \ and Secret Keys.\r\n"
home: https://github.com/truecharts/apps/tree/master/charts/stable/s3sync
icon: https://truecharts.org/_static/img/appicons/s3sync.png
keywords:
- s3sync
- *id001
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: s3sync
sources:
- https://github.com/what-name/docker-s3sync
- https://hub.docker.com/repository/docker/whatname/docker-s3sync
type: application
version: 0.0.1
