annotations:
  truecharts.org/SCALE-support: 'true'
  truecharts.org/catagories: |
    - Tools-Utilities
  truecharts.org/grade: U
apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.6
deprecated: false
description: A small flask based service to sync up Emby clients
home: https://github.com/truecharts/apps/tree/master/charts/stable/emby-sync
icon: https://truecharts.org/_static/img/appicons/emby-sync.png
keywords:
- emby-sync
- Tools-Utilities
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: emby-sync
sources:
- https://github.com/cameronurnes/emby-sync
- https://hub.docker.com/r/lastelement21/emby-sync/
type: application
version: 0.0.1
